## DB setting
server:
  tomcat:
    max-swallow-size: -1

spring:
  profiles:
    ##application-secret에 들어간 요소
    #jwt.secretKey
    ##spring.datasource.password
    include: secret
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    ## MaxUploadSizeExceededException
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.hknusc.web.domain
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-handlers-package: com.hknusc.web.util.typeHandler

photo:
  uploadPath: C:\\workspace\\publicminsu\\Image\\
