## DB setting
server:
  tomcat:
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:postgresql://svc.sel4.cloudtype.app:30556/postgres
    username: root
    driver-class-name: org.postgresql.Driver
    ## MaxUploadSizeExceededException
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.hknusc.web.domain
  type-handlers-package: com.hknusc.web.util.typeHandler
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true