CREATE EXTENSION IF NOT EXISTS CUBE;
CREATE EXTENSION IF NOT EXISTS EARTHDISTANCE;
CREATE TABLE ACCOUNT 
(
	Id SERIAL PRIMARY KEY,
	Email TEXT UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	NICKNAME TEXT UNIQUE NOT NULL,
	PHONE_NUMBER TEXT UNIQUE NOT NULL,
	PAYMENT_CARD TEXT,
	IS_VERIFIED BOOLEAN NOT NULL
);
CREATE TABLE DELETED_ACCOUNT 
(
	Id SERIAL PRIMARY KEY,
	Email TEXT UNIQUE NOT NULL,
	PHONE_NUMBER TEXT UNIQUE NOT NULL,
	DELETE_TIME TIMESTAMP NOT NULL
);
CREATE TABLE STORE
(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	NAME TEXT NOT NULL,
	LATITUDE FLOAT8 NOT NULL,
	LONGITUDE FLOAT8 NOT NULL,
	ADDRESS TEXT,
	INFO TEXT,
	PHONE_NUMBER TEXT,
	CAN_RESERVATION BOOL,
	OPERATING_TIME TEXT,
	IS_OPEN BOOL
);
CREATE TABLE REVIEW
(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	STORE_ID INT NOT NULL,
	DETAIL TEXT,
	WRITING_TIME TIMESTAMP NOT NULL,
	RATING INT NOT NULL
);
CREATE TABLE MENU
(
	ID SERIAL PRIMARY KEY,
	STORE_ID INT NOT NULL,
	NAME TEXT NOT NULL,
	PRICE INT NOT NULL,
	PHOTO TEXT,
	CATEGORY TEXT
);
CREATE TABLE TABLE_ITEM
(
	ID SERIAL PRIMARY KEY,
	STORE_ID INT NOT NULL,
	NAME TEXT,
	COORD_X TEXT NOT NULL,
	COORD_Y TEXT NOT NULL,
	WIDTH TEXT NOT NULL,
	HEIGHT TEXT NOT NULL,
	PRIVATE_KEY TEXT NOT NULL
);
CREATE TABLE ORDER_ITEM
(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	STORE_ID INT NOT NULL,
	TABLE_ID INT NOT NULL,
	ORDER_TIME TIMESTAMP,
	PAYMENT_TIME TIMESTAMP,
	RESERVATION_TIME TIMESTAMP,
	ORDER_CODE SMALLINT NOT NULL,
	RESERVATION_DENY_DETAIL Text
);
CREATE TABLE ORDER_DETAIL
(
	ID SERIAL PRIMARY KEY,
	ORDER_ID INT NOT NULL,
	MENU_ID INT NOT NULL,
	AMOUNT INT NOT NULL
);
CREATE TABLE AUTH
(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT UNIQUE NOT NULL,
	REFRESH_TOKEN TEXT
)
/*
	WISH_LIST,
	COUPON_LIST
*/