INSERT INTO ACCOUNT(EMAIL,PASSWORD,NICKNAME,PHONE_NUMBER) 
	VALUES ('EMAIL1','TEMP','TEMP','010');
INSERT INTO ACCOUNT(EMAIL,PASSWORD,NICKNAME,PHONE_NUMBER) 
	VALUES ('EMAIL2','TEMP','TEMP1','012');

SELECT * FROM ACCOUNT;

INSERT INTO STORE(ACCOUNT_ID,NAME,INFO) 
	VALUES (1,'김치집','김치가 맛있어요');

SELECT * FROM STORE;